import { CAlert } from "https://06fs4dix.github.io/Artgine/artgine/basic/CAlert.js";
import { CLan } from "https://06fs4dix.github.io/Artgine/artgine/basic/CLan.js";
import { CAtelier } from "https://06fs4dix.github.io/Artgine/artgine/canvas/CAtelier.js";
import { CColor } from "https://06fs4dix.github.io/Artgine/artgine/canvas/component/CColor.js";
import { CPaint2D } from "https://06fs4dix.github.io/Artgine/artgine/canvas/component/paint/CPaint2D.js";
import { CSubject } from "https://06fs4dix.github.io/Artgine/artgine/canvas/subject/CSubject.js";
import { CVec2 } from "https://06fs4dix.github.io/Artgine/artgine/geometry/CVec2.js";
import { CVec3 } from "https://06fs4dix.github.io/Artgine/artgine/geometry/CVec3.js";
import { CH5Canvas } from "https://06fs4dix.github.io/Artgine/artgine/render/CH5Canvas.js";
let gAtl = CAtelier.Main();
CLan.Set(CLan.eType.en, "Test0", "Code has been executed.<br>You can restart by refreshing with F5");
CAlert.Info(CLan.Get("Test0", "Code를 실행했습니다.<br>새로고침으로 다시 시작할수 있습니다.F5"), 1000 * 10);
let can = gAtl.Canvas("2DCan");
let sub = can.Push(new CSubject());
let pt = sub.PushComp(new CPaint2D(gAtl.Frame().Pal().GetNoneTex(), new CVec2(100, 100)));
sub.SetPos(new CVec3(200, 200));
pt.SetColorModel(new CColor(0, 1, 0, CColor.eModel.RGBMul));
CH5Canvas.Init(256, 256);
CH5Canvas.FillStyle("green");
CH5Canvas.FillRect(0, 0, 256, 256);
CH5Canvas.FillStyle("orange");
CH5Canvas.FillText(128, 128, "test", 128);
CH5Canvas.Draw();
let tex = CH5Canvas.GetNewTex();
gAtl.Frame().Ren().BuildTexture(tex);
gAtl.Frame().Res().Push("test.tex", tex);
sub = can.Push(new CSubject());
pt = sub.PushComp(new CPaint2D("test.tex", new CVec2(100, 100)));
sub.SetPos(new CVec3(-200, 200));
